### PR TITLE
Redo pull request #228 against latest build

### PR DESCRIPTION
**Pull request by cunneen**
Allow fluid containers and rows.
Updated version of pull request #228, performed against latest master. 
/cc @fix

### CODE REVIEW

**Comment by fix** [comment]
thanks cunneen, Travis is failing because of some test compilation error.

I am fixing it first. Thanks for resubmiting!

**Comment by cunneen** [comment]
You're welcome.
There will be a merge conflict if/when you get to #346 (I wasn't sure how best to separate these). All four lines of entry.coffee should be included, to ensure it doesn't break people's existing installations:

(from line 12)
```coffee
    fluidLayout: false
    useContainer: true
    signInAfterRegistration: true
    emailVerificationPendingRoute: '/verification-pending'
```

I'll make a note against #346 too.

**Comment by cunneen** [comment]
@fix , try merging #348 first.

**Comment by fix** [comment]
ok i have something weird where the tests are looping for ever on travis.

Any idea ?

**Comment by fix** [comment]
Can you document the README as well
Thanks!

**Comment by cunneen** [comment]
No idea, but I did notice this. Eventually, the tinytest patch finished.

When I tested the package locally (meteor test-package) this didn't occur, so I think it's more to do with travis.

**Comment by cunneen** [comment]
Sure, but it probably won't be until tomorrow.

Apologies, it didn't even occur to me to update the README.

**Pull request merged**
