### PR TITLE
Add new classes to allow fluid bootstrap containers and rows

### PR DESCRIPTION
**Pull request by cunneen**
Add new CSS classes to allow fluid bootstrap containers and rows.
Also allow suppression of the CSS class for the container div (for cases where it's already in a container).
New settings and defaults:
    fluidLayout: false
    useContainer: true

Also fix issue with unit tests in tests/client.coffee for Meteor 0.8.3

### CODE REVIEW

**Comment by fix** [comment]
Hi, is it possible to merge this PR, this is really useful, otherwise I am hacking around my own template.

**Comment by queso** [comment]
Happy to give someone commit rights if they want.

**Comment by fix** [comment]
Well, I am ok for that, I'll try to clean up all the PR around

**Comment by queso** [comment]
actually, @ryw would have to do that, I don't have the rights on this repo.

**Comment by ryw** [comment]
@fix it is done :)

**Comment by fix** [comment]
Nice thanks!

**Comment by fix** [comment]
I'll make a new version with the PR that could be merged

**Pull request closed without merging**
